### PR TITLE
Allow for a missing datasource

### PR DESCRIPTION
**Pull request by jonkeda**
Allow for a missing datasource which means that the datasource is a FullUri like:

FullUri=file::memory:?cache=shared;Version=3

This way the in memory database can be shared over connections.

### CODE REVIEW

**Comment by jonkeda** [comment]
Support Database Default values specified using a custom attribute #85

**Comment by msallin** [comment]
Hi @jonkeda 

Thank you for the PR.

Some suggestions.

1. I think its not necessary to change the InMemoryAwareFile and the ConnectionStringParser.
The ConnectionStringParser can just check for `connectionString.Contains(":memory:");`
If the path contains this, it is a InMemory db (for both cases).

2. If I understand this correctly you want to support FullURIs for files.
This PR treats all FullURIs as in memory db. Shouldn't it then also be supported to do smth link "file://darkstar/home/fred/data.db"? Its not necessary for your scenario, so you don't have it to implement but I'm going to create a issue for it.

3. Default Value
Can you use smth different than DateTime.Now? E.g. a fixed Date.
Because I've a very rudimentary integration test to ensure that I don't introduce regression (SqlGenerationTest). There I need to know which values will be generated.
It would also be great if you can run this test (it only runs when triggered manually because of a conflict with the "MemoryDbTest" on the build server) and make sure that it passes.

Cheers, Marc

**Comment by jonkeda** [comment]
Hi @msallin,

1. I needed to change the connectionparser also because it failed if no datasource was set in the connectionstring. I agree that it would be better to fully support the FullUri. But I couldn't fully oversee the necessary changes to be made, so I went with the 'lazy' least amount of changes option.

2. I wanted to have fulluri for memory db's and set the shared cache switch. This made it possible to create unittests for the SqlQueries project and another in company project.

3. I changed the SqlGenerationTest expected string. I used the DateTime.Now function, I didn't see a check on the actual values, but only on the generated statement. I didn't see the sqlgenerationtest before, sorry I missed it. I am trying to fix it, but probably need to do a number of PR's to test the buildserver. I hope you don't mind.

Kind regards,
Daan

**Comment by jonkeda** [comment]
Hi Marc,

AppVeyor says that the build has succeeded and I did remove the Ignore on the SqlGenerationTest. 

Could you please have a look and check if it is correct?

Regards,
Daan

**Comment by msallin** [comment]
1. True. But wouldn't it be easier to just check if :memory: is present somewhere in the string and return this instead of null? This means that all works like it does now but also file::memory: is supported. And the only change necessary is in the ConnectionStringParser. Even we can prepare the code for implementing FileUri. Like this:

```
public static string GetDataSource(string connectionString)
{
    // If the datasource token does not exists this is a FullUri connection string.
    IDictionary<string, string> strings = ParseConnectionString(connectionString);
    if (strings.ContainsKey(DataSourceToken))
    {
        var path = ExpandDataDirectory(ParseConnectionString(connectionString)[DataSourceToken]);
        // remove quotation mark if exists
        return path.Trim('"');
    } 
    else 
    {
        // TODO: Implement FullUri parsing.
        if(connectionString.Contains(":memory:"));
        {
            return ":memory:";
        }
        else
        {
            throw new NotSupportedExceptions("FullUri format is currently only supported for :memory:.");
        }
    }
}
```
What do you think?

3. Of course... :) Oh, cool that it works now.

**Comment by jonkeda** [comment]
Hi Marc,

1. Yep, that is a better idea. I updated it. Resharper had some comments so I followed those. 

3. Great.

And thanks for the great piece of work. It saved me a lot of time in building unitests for a company system.

Kind regards,
Daan

**Pull request merged**
